changed for testing

diff --git a/.github/workflows/sonar.yaml b/.github/workflows/sonar.yaml
--- a/.github/workflows/sonar.yaml
+++ b/.github/workflows/sonar.yaml
@@ -40,8 +40,8 @@ jobs:
           echo "| Step | Status |" >> $GITHUB_STEP_SUMMARY
           echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
           echo "| Checkout | ✅ Success |" >> $GITHUB_STEP_SUMMARY
-          echo "| SonarQube Scan | $([[ '${{ steps.sonarqube-scan-check.outcome }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
-          echo "| SonarQube Quality Gate | $([[ '${{ steps.sonarqube-quality-check.outcome }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
+          echo "| SonarQube Scan Test | $([[ '${{ steps.sonarqube-scan-check.outcome }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
+          echo "| SonarQube Quality Gate Test | $([[ '${{ steps.sonarqube-quality-check.outcome }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
         
   push_to_registry:
     name: Push Docker image to Docker Hub
