sonar local

diff --git a/.github/workflows/sonar.yaml b/.github/workflows/sonar.yaml
--- a/.github/workflows/sonar.yaml
+++ b/.github/workflows/sonar.yaml
@@ -3,7 +3,7 @@ name: Build and Test App
 on:
   push:
     branches:
-      - dev
+      - stage
     tags:
       - '*'
   pull_request:
@@ -20,9 +20,17 @@ jobs:
 
       - name: SonarQube Scan
         id: sonarqube-scan-check
-        uses: SonarSource/sonarqube-scan-action@v5
+        uses: sonarsource/sonarqube-scan-action@master
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_2 }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+      - name: SonarQube Quality Gate
+        id: sonarqube-quality-check
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        timeout-minutes: 5
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_2 }}
 
       - name: Summarize SonarQube job
         if: always()
@@ -33,3 +41,4 @@ jobs:
           echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
           echo "| Checkout | ✅ Success |" >> $GITHUB_STEP_SUMMARY
           echo "| SonarQube Scan | $([[ '${{ steps.sonarqube-scan-check.outcome }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
+          echo "| SonarQube Quality Gate | $([[ '${{ steps.sonarqube-quality-check }}' == 'success' ]] && echo ✅ Success || echo ❌ Failed) |" >> $GITHUB_STEP_SUMMARY
